### ISSUE TITLE
Turtle date

### ISSUE THREAD

**Issue by RyanDou** [dbca-wa/wastd#335]
## Problem

Allowing grouping of observations by the older method of 'turtle date'
## Feature

Add a column in WAStD that has automatically calculated the 'turtle date' of the track that was observed as in the image below
![image](https://user-images.githubusercontent.com/11881636/92361100-7c026280-f120-11ea-9269-48f8fcdf243f.png)

## Tasks

- [ ] Add model property turtle_date to Encounter, AnimalEncounter, TurtleNestEncounter, 
- [ ] expose turtle_date via admin, API, GUI, 
- [ ] add filters on turtle_date for admin, API, GUI, 
- [ ] add examples to docs.

**Comment by florianm** [comment]
Add model property `turtle_date` to Encounter, AnimalEncounter, TurtleNestEncounter, expose via admin, API, GUI, add filters for admin, API, GUI, add examples to docs.
